# Configuration for your trading application

exchange = "bybit" # Name of the exchange you're connecting to (e.g., bybit, binance, both)

# List of symbols to track and trade
symbols = ["NOTUSDT"] # Replace with your desired symbols

# API keys for authentication (potentially multiple keys for redundancy)
api_keys = [["api_key_1", "api_secret_1", "NOTUSDT"]]

# Initial balances for tracked symbols (symbol, balance)
balances = [["NOTUSDT", 100.0]]

# Leverage for trading positions (e.g., 5.0 for 5x leverage)
leverage = 12.0

# Maximum number of orders to place on each side of the market
orders_per_side = 4

# Final order distance for orders (e.g., 10 for 10 * 25bps = 250bps or 2.5%)
final_order_distance = 10

# Periodic update interval in secs for stale orders
update_interval = 60

# Number of order book levels (depth) to request from the exchange
depths = [3, 8, 34] # You can have multiple depths for different symbols

# Rate limit for API calls (in secs)
rate_limit = 10

# Profit spread for  (e.g., 1 for 0.01% profit spread)
bps = [27]

# use tick window for waiting and lookback period 1 tick = 10ms  , 100 ticks = 1s, 6000 ticks for 1m
tick_window = 8000 # 100secs = 10,000
