# Configuration for your trading application

exchange = "bybit" # Name of the exchange you're connecting to

# List of symbols to track and trade
symbols = ["ETHUSDT"] # Replace with your desired symbols

# API keys for authentication (potentially multiple keys for redundancy)
api_keys = [
  [
    "api_key_1",
    "api_secret_1",
    "NOTUSDT",
  ],
  [
    "api_key_2",
    "api_secret_2",
    "DOGSUSDT",
  ],
]

# Initial balances for tracked symbols (symbol, balance)
balances = [["BTC", 0.1], ["ETH", 1.0]]

# Leverage for trading positions (e.g., 5.0 for 5x leverage)
leverage = 2.0

# Maximum number of orders to place on each side of the market
orders_per_side = 3

# Final order distance for trailing stop orders (e.g., 0.01 for 1% price difference)
final_order_distance = 0.005

# Number of order book levels (depth) to request from the exchange
depths = [10, 20] # You can have multiple depths for different symbols

# Rebalance ratio for portfolio management (e.g., 0.1 for 10% rebalance)
rebalance_ratio = 0.05

# Rate limit for API calls (in milliseconds)
rate_limit = 1000

# Profit spread for  (e.g., 1 for 0.01% profit spread)
bps = [27, 25]

# use wmid when calculating 
use_wmid = true