[package]
name = "skeleton"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binance = "0.20.2"
ordered-float = "4.2.0"
rs_bybit = "0.1.3"
serde = "1.0.197"
tokio = "1.36.0"
